# Generated by Django 4.2.3 on 2023-07-26 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("showroomapp", "0002_alter_brand_options_alter_engine_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="showroom",
            old_name="address",
            new_name="location",
        ),
    ]
